# Generated by Django 3.2 on 2021-11-27 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='category of ')),
                ('estado', models.CharField(choices=[('1', 'Active'), ('0', 'Deleted')], default='1', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Platillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('small', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('toppings', models.PositiveIntegerField(blank=True, default=0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.categorias')),
            ],
        ),
        migrations.RenameModel(
            old_name='cart',
            new_name='Carrito',
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='Toppings',
        ),
        migrations.RemoveField(
            model_name='saucer',
            name='category',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='product',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='toppings',
            old_name='top',
            new_name='topping',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='saucer',
        ),
    ]
