# Generated by Django 3.2.9 on 2021-11-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category of ')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Deleted')], default='1', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
