# Generated by Django 3.2 on 2021-11-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211127_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='platillos',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Platillos',
        ),
    ]
