# Generated by Django 3.2 on 2021-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211130_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='max_extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='max_extras',
            field=models.IntegerField(default=0),
        ),
    ]
