# Generated by Django 3.2 on 2021-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211130_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='approved',
        ),
    ]
