# Generated by Django 3.2 on 2021-12-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_detalleorden_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
