# Generated by Django 3.2 on 2021-12-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211201_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='order',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='toppingsList',
        ),
        migrations.DeleteModel(
            name='CarritoOrdenes',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
    ]
