# Generated by Django 3.2 on 2021-12-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_detalleorden_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name_plural': 'DetalleOrden'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Orden'},
        ),
    ]
