# Generated by Django 3.2 on 2021-12-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20211201_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('order', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('approved', models.CharField(default='None', max_length=10)),
            ],
        ),
    ]
