# Generated by Django 3.2 on 2021-12-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orden_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('0', 'creada'), ('1', 'progreso'), ('2', 'finalizado'), ('3', 'cancelado')], default='0', max_length=10),
        ),
    ]
